Repository NookPost/nookpost-frontend, pull requests merged in 2025-02, with the labels that each got.

#4 feature/main layout
  Licenses/OpenAPI-Generator
  Licenses/Pinia
  Licenses/PrimeVue
  Licenses/Vue
  Licenses/Vue-Advanced-Cropper
  Licenses/Vue-router
  assets/swagger.json
  openapitools.json
  package-lock.json
  package.json
  src/App.vue
  src/api/.gitignore
  src/api/.npmignore
  src/api/.openapi-generator-ignore
  src/api/.openapi-generator/FILES
  src/api/.openapi-generator/VERSION
  src/api/api.ts
  src/api/base.ts
  src/api/common.ts
  src/api/configuration.ts
  src/api/git_push.sh
  src/api/index.ts
  src/assets/base.css
  src/assets/form-center.css
  src/assets/logo.svg
  src/assets/main.css
  src/assets/post-grid.css
  src/assets/post.css
  src/assets/profile.css
  src/components/Base64Cropper.vue
  src/components/HelloWorld.vue
  src/components/PostDetail.vue
  src/components/PostPreview.vue
  src/components/PostPreviewGrid.vue
  src/components/SearchBar.vue
  src/components/TopBar.vue
  src/components/UserProfile.vue
  src/components/WelcomeItem.vue
  src/main.ts
  src/router/index.ts
  src/store/auth.ts
  src/types/post.ts
  src/types/profile.ts
  src/util/api.ts
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/PostDetailView.vue
  src/views/RegisterView.vue
  src/views/UserProfile.vue
Labels: enhancement

#5 User profile show posts
  src/assets/profile.css
  src/components/UserProfile.vue
  src/views/UserProfile.vue
Labels: enhancement

#7 Impressum rename to proper translation
  src/assets/base.css
  src/components/PostDetail.vue
  src/components/PostPreview.vue
  src/components/TopBar.vue
  src/router/index.ts
Labels: bug

#9 category overview
  src/App.vue
  src/assets/frame.css
  src/components/CategoryItem.vue
  src/router/index.ts
  src/types/category.ts
  src/views/CategoriesView.vue
Labels: enhancement

#12 add release action to docker workflow
  .github/workflows/docker.yml
Labels: documentation, enhancement

#10 editable post component
  Licenses/Quill
  package-lock.json
  package.json
  src/assets/form-center.css
  src/assets/frame.css
  src/assets/post.css
  src/assets/profile.css
  src/components/PostDetail.vue
  src/components/PostPreview.vue
  src/components/UserProfile.vue
  src/main.ts
  src/types/post.ts
  src/views/HomeView.vue
  src/views/PostDetailView.vue
Labels: enhancement

#13 editable Profile
  src/assets/crop-dialog.css
  src/assets/post.css
  src/assets/profile.css
  src/components/Base64Cropper.vue
  src/components/CropperDialog.vue
  src/components/PostDetail.vue
  src/components/UserProfile.vue
  src/main.ts
  src/types/userSettings.ts
  src/views/PersonalProfileView.vue
  src/views/UserProfile.vue
Labels: enhancement

#14 Refactored some login stuff
  src/store/auth.ts
  src/views/LoginView.vue
  src/views/RegisterView.vue
Labels: enhancement

#17 Categories store
  src/store/categories.ts
  src/views/CategoriesView.vue
Labels: enhancement

#18 Made post detail view fetch the post when being loaded
  src/view-api-interaction/PostDetailView.ts
  src/views/PostDetailView.vue
Labels: enhancement

#23 added loading spinner to post detail view + post edit to router
  src/router/index.ts
  src/views/PostDetailView.vue
Labels: enhancement

#21 Fixed category not being loaded by post
  src/view-api-interaction/PostDetailView.ts
Labels: bug

#24 Css touchups
  src/App.vue
  src/assets/form-center.css
  src/assets/frame.css
  src/assets/post.css
  src/assets/profile.css
  src/components/CategoryItem.vue
  src/components/PostDetail.vue
  src/components/PostPreview.vue
  src/components/UserProfile.vue
  src/views/CategoriesView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/RegisterView.vue
Labels: enhancement

#25 added post create button + according view
  src/assets/post.css
  src/components/TopBar.vue
  src/router/index.ts
  src/views/CreatePostView.vue
  src/views/PostDetailView.vue
Labels: bug, enhancement

#28 Added home view fetching posts
  src/main.ts
  src/router/index.ts
  src/view-api-interaction/HomeView.ts
  src/views/HomeView.vue
Labels: enhancement

#30 fix(docker): fixed 404 on subpath
  Dockerfile
  docker-compose.yml
  nginx-conf.d/default.conf
Labels: bug

#31 Post username displayname
  assets/swagger.json
  src/api/.openapi-generator/FILES
  src/api/api.ts
  src/api/api/categories-api.ts
  src/api/api/posts-api.ts
  src/api/api/users-api.ts
  src/api/api/users-settings-api.ts
  src/api/apis/authentication-api.ts
  src/api/apis/posts-api.ts
  src/api/apis/user-settings-api.ts
  src/api/apis/users-api.ts
  src/api/models/get-post-filtered-post.ts
  src/api/models/get-post-response-body.ts
  src/api/models/put-post-request-body.ts
  src/api/models/users-get-response-body.ts
  src/assets/post.css
  src/components/PostDetail.vue
  src/components/PostPreview.vue
  src/store/categories.ts
  src/types/post.ts
  src/view-api-interaction/HomeView.ts
  src/view-api-interaction/PostDetailView.ts
  src/views/PersonalProfileView.vue
  src/views/PostDetailView.vue
  src/views/UserProfile.vue
Labels: enhancement

#33 Post edit and delete button
  src/assets/post.css
  src/components/PostPreview.vue
  src/store/auth.ts
Labels: enhancement

#34 Settings view
  src/assets/settings.css
  src/types/userSettings.ts
  src/views/UserSettingsView.vue
Labels: enhancement

#32 Connected the user profile page to the API
  src/components/UserProfile.vue
  src/types/profile.ts
  src/view-api-interaction/UserProfile.ts
  src/views/PersonalProfileView.vue
  src/views/UserProfile.vue
Labels: enhancement

#36 fix post category link
  src/components/PostDetail.vue
  src/components/PostPreview.vue
Labels: bug

#37 Connected category detail view to API
  src/view-api-interaction/CategoryDetailView.ts
  src/views/CategoryDetailView.vue
Labels: enhancement

#39 fix css + add edit and delete button
  src/assets/post.css
  src/components/PostDetail.vue
Labels: bug, enhancement

#41 Connected own user profile to fetch profile from API
  src/view-api-interaction/PersonalProfileView.ts
  src/views/PersonalProfileView.vue
Labels: enhancement

#42 Added connection to API for post deletion
  src/component-api-interaction/PostDeletion.ts
  src/components/PostDetail.vue
  src/components/PostPreview.vue
Labels: enhancement

#43 Connected search view to API
  src/view-api-interaction/SearchResultsView.ts
  src/views/SearchResultsView.vue
Labels: enhancement

#44 Added post create dialog API connection
  src/components/PostDetail.vue
  src/view-api-interaction/PostDetailView.ts
  src/views/PostDetailView.vue
Labels: enhancement

#45 Fixed the truncating body on post preview
  src/components/PostPreview.vue
Labels: bug

#46 Fixed register not mapping display name correctly
  src/views/RegisterView.vue
Labels: bug

#47 Made visiting own profile redirect to personal profile
  src/views/UserProfile.vue
Labels: enhancement

#48 Connected personal profile edit to API
  src/view-api-interaction/PersonalProfileView.ts
  src/views/PersonalProfileView.vue
Labels: enhancement

#49 Changed success check on API to include all 2XX codes
  src/component-api-interaction/PostDeletion.ts
  src/store/auth.ts
  src/store/categories.ts
  src/view-api-interaction/CategoryDetailView.ts
  src/view-api-interaction/HomeView.ts
  src/view-api-interaction/PersonalProfileView.ts
  src/view-api-interaction/PostDetailView.ts
  src/view-api-interaction/SearchResultsView.ts
  src/view-api-interaction/UserProfile.ts
Labels: enhancement

#50 removed unneeded escaping, added default value and fixed url not gett…
  1-update-api-url.sh
Labels: bug

#52 Api refactoring
  src/api-calls/posts.ts
  src/api-calls/users.ts
  src/component-api-interaction/PostDeletion.ts
  src/components/PostDetail.vue
  src/components/PostPreview.vue
  src/main.ts
  src/view-api-interaction/CategoryDetailView.ts
  src/view-api-interaction/HomeView.ts
  src/view-api-interaction/PersonalProfileView.ts
  src/view-api-interaction/PostDetailView.ts
  src/view-api-interaction/SearchResultsView.ts
  src/view-api-interaction/UserProfile.ts
  src/views/CategoryDetailView.vue
  src/views/HomeView.vue
  src/views/PersonalProfileView.vue
  src/views/PostDetailView.vue
  src/views/SearchResultsView.vue
  src/views/UserProfile.vue
Labels: enhancement

#58 Added docs for API connection
  src/api-calls/posts.ts
  src/api-calls/users.ts
Labels: documentation
